# Generated by Django 5.0.3 on 2024-03-06 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='title',
            field=models.CharField(default='a', max_length=255),
        ),
    ]
