# Generated by Django 5.0.3 on 2024-03-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_chatbot', '0002_fileupload_uploaded_at_alter_fileupload_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='title',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
