# Generated by Django 5.0.3 on 2024-03-06 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_chatbot', '0006_alter_fileupload_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='doc_file',
            new_name='file_path',
        ),
    ]
